### ISSUE TITLE
Function init() does not executing

### ISSUE THREAD

**Issue by alepn** [ofkindness/winston-sql-transport#13]
Hi!

The logs table is not being created, because the function init() does not executing when I run the project.

My project is on NestJS.

It works when I added a call of init() on constructor of SQLTransport.

**Comment by ofkindness** [comment]
Hello @alepn this function return Promise, did you use **await** ?

**Comment by alepn** [comment]
Ok, I'll try this.

I noticed too that logs is not inserting.

So a have to change this line:

`const logQuery = () => client.insert(log).into(tableName);` 

To this:

`const logQuery = async () => await client.insert(log).into(tableName);` 

Then it works!

You know why?

**Comment by ofkindness** [comment]
these are two equivalent function notations, the second is redundant

**Comment by ofkindness** [comment]
It's actually make sense, I'll push fix asap

**Comment by ofkindness** [comment]
thank you @alepn for provided information, please consider the update from new tag https://github.com/ofkindness/winston-sql-transport/releases/tag/2.2.0

**Comment by alepn** [comment]
Ok! Thank you!
